version: '3.8'

services:
  social-service:
    build: .
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - JWT_SECRET=${JWT_SECRET}
      - QUIZ_SERVER_URL=https://romantic-nanete-adildevelopment-3ec66986.koyeb.app
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - mongo
      - Redis
      - rabbitmq
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=social_microservice

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
